# Generated by Django 6.0.1 on 2026-01-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='key',
            field=models.CharField(default='-*#-', max_length=10),
        ),
    ]
