# Generated by Django 6.0.1 on 2026-01-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_gamehistory_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='key',
            field=models.CharField(max_length=4),
        ),
    ]
