# Generated by Django 6.0.1 on 2026-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_alter_gamehistory_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
