# Generated by Django 6.0.1 on 2026-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TounamenTHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
