# Generated by Django 6.0.1 on 2026-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_tounamenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(),
        ),
    ]
