# Generated by Django 6.0.1 on 2026-01-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_alter_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tounamenthistory',
            name='date',
            field=models.DateField(),
        ),
    ]
