# Generated by Django 6.0.1 on 2026-01-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_alter_tounamenthistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tounamenthistory',
            name='username',
            field=models.CharField(default='mohammedimran', max_length=250),
        ),
    ]
