# Generated by Django 6.0.1 on 2026-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_alter_tounamenthistory_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tounamenthistory',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tounamenthistory',
            name='input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tounamenthistory',
            name='key',
            field=models.CharField(default=' ', max_length=4),
        ),
        migrations.AddField(
            model_name='tounamenthistory',
            name='status',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
