# Generated by Django 6.0.1 on 2026-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_tounamenthistory_attempt_tounamenthistory_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tounamenthistory',
            name='input',
            field=models.IntegerField(),
        ),
    ]
