# Generated by Django 6.0.1 on 2026-01-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_alter_tounamenthistory_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tounamenthistory',
            name='input',
        ),
    ]
