# Generated by Django 6.0.1 on 2026-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_remove_tounamenthistory_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tounamenthistory',
            name='key',
            field=models.CharField(default=' ----', max_length=4),
        ),
        migrations.AlterField(
            model_name='tounamenthistory',
            name='status',
            field=models.CharField(default='you win', max_length=50),
        ),
    ]
