# Generated by Django 6.0.1 on 2026-01-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_alter_tounamenthistory_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tounamenthistory',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='tounamenthistory',
            name='key',
        ),
        migrations.RemoveField(
            model_name='tounamenthistory',
            name='status',
        ),
    ]
