# Generated by Django 6.0.1 on 2026-01-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0015_remove_tounamenthistory_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tounamenthistory',
            name='username',
        ),
    ]
