# Generated by Django 6.0.1 on 2026-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0017_tounamenthistory_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tounamenthistory',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
